#!sh

set -eo pipefail
[[ -z "$TRACE" ]] || set -x

command -v "$1" >/dev/null 2>&1 && exec "$@"
set -- 
. tomcat-configurator
. timezone-configurator
. log4j-configurator
. crowd-sso-configurator
. jira-servicedesk-configurator

. environment-hygiene

echo "$@"
exec /usr/bin/env - "$@"